<?php
return [
    'key_firebase' => 'AAAA0i5VEtw:APA91bGn6K6XM-GK2RHqFVi7W3Iz3JqLcCrz7wgmfI2Ab2TcKWn1fzdyDJumPtmEaR7NP2udSTBEGKbhIyuO46jPF_hrB9MSPkgo9KnO-mqBy6kAmNtPFq60hLUAUVwT8Ul_5LWvWUvB',
    'DB_HOST_STORAGE' => "http://127.0.0.1:8000",
    'paginate_size' => [
        'default' => 10,
        'list' => [10, 20, 50, 100],
    ],
    'gioi_tinh' => [
        'Nam',
        'Nữ',
    ],
    'do_tuoi' => [
        'tuoi_2'=> 2,
        'tuoi_3'=> 3,
        'tuoi_4'=> 4,
        'tuoi_5'=> 5,
    ],
    'trang_thai_hoc_sinh' => [
        'chưa có lớp','đang học','thôi học','ra trường'
    ],
    'dan_toc' => [
        'Kinh',
        'Tày',
        'Thái',
        'Mường',
        'Hoa',
        'Khmer',
        'Nùng',
        'HMông',
        'Dao',
        'Gia-rai',
        'Ê-đê',
        'Ba-na',
        'Sán Chay',
        'Chăm',
        'Xê Đăng',
        'Sán Dìu',
        'Hrê',
        'Cơ-Ho',
        'Ra Glay',
        'M\'ông',
        'Thổ',
        'Xtiêng',
        'Khơ Mú',
        'Bru-Vân Kiều',
        'Giáy',
        'Cơ tu',
        'Gié-Triêng',
        'Ta Ôi',
        'Mạ',
        'Co',
        'Chơ Ro',
        'Hà Nhì',
        'Xinh Mun',
        'Chu-ru',
        'Lào',
        'La Chí',
        'Phù Lá',
        'La Hủ',
        'Kháng',
        'Lự',
        'Pà Thẻn',
        'Lô Lô',
        'Chứt',
        'Mảng',
        'Cờ lao',
        'Bố Y',
        'La Ha',
        'Cống',
        'Ngái',
        'Si La',
        'Pu Péo',
        'Brâu',
        'Rơ Măm',
        'Ơ Đu'
    ] 
]
?>
